name = "Eternal"
author = "oDevEric"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d13907cfadbf7c507d3737a8ca8b0dfa9235bfd2dfcf3b2256f6f1bc1472646"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
