name = "Eternal"
author = "oDevEric"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23459a3c7a0ce1c181918d6959e4872f321ae48db953d0300e7bdd8974f4034f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
