name = "Eternal"
author = "oDevEric"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "280eb8ebcb9aca93bda41b5c9787fd6d669e55098fdc647eb50298d298725548"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
